<?php
/**
 * Created by PhpStorm.
 * User: Liza
 * Date: 02.04.2019
 * Time: 23:06
 */

namespace app\modules\admin\controllers;

use yii\web\Controller;
use yii\filters\AccessControl;

class AppAdminController extends Controller
{
    protected function setMeta($title = null, $keywords = null, $description = null){
        $this->view->title = $title;
        $this->view->registerMetaTag(['name' => 'keywords', 'content' => "$keywords"]);
        $this->view->registerMetaTag(['name' => 'description', 'content' => "$description"]);
    }

        public function behaviors()
        {
            return [
                'access' => [
                    'class' => AccessControl::className(),
                    'only' => ['login', 'logout', 'signup'],
                    'rules' => [
//                        [
//                            'allow' => true,
//                            'actions' => ['login', 'signup'],
//                            'roles' => ['?'],
//                        ],
                        [
                            'allow' => true,
//                            'actions' => ['logout'],
                            'roles' => ['@'],
                        ],
                    ],
                ],
            ];

//            return parent::behaviors(); // TODO: Change the autogenerated stub
        }
}