version: '3.2'

volumes:
  db-data:

networks:
  mynet:

services:
  php-beltelecom:
    build:
      context: ./
      dockerfile: ./docker/php-fpm/dev/Dockerfile
    container_name: "php.beltelecom"
    volumes:
      - type: bind
        source: ./
        target: /var/www/html
    environment:
      - XDEBUG_CONFIG='idekey=xdebug; xdebug.remote_host=192.168.0.115'
      - PHP_IDE_CONFIG=serverName=docker-api
      - YII_DEBUG=true
      - YII_ENV=prod
      - DB_DNS=mysql:host=mysql-beltelecom:3306;dbname=my_logodom
      - DB_USER=user_logodom
      - DB_PASSWORD=password_logodom
    depends_on:
      - mysql-beltelecom
    networks:
      - mynet

  nginx-beltelecom:
    build: ./docker/nginx/prod/
    container_name: "nginx.beltelecom"
    ports:
      - 80:80
      - 443:443
    volumes:
      - type: bind
        source: ./
        target: /var/www/html/
    depends_on:
      - php-beltelecom
    environment:
      - CERTBOT_DOMAINS=beltelecom.by
    networks:
      - mynet
    links:
      - php-beltelecom

  mysql-beltelecom:
    build:
      context: ./
      dockerfile: ./docker/mysql/dev/Dockerfile
    container_name: "mysql.beltelecom"
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=my_logodom
      - MYSQL_USER=user_logodom
      - MYSQL_PASSWORD=password_logodom
      - MYSQL_ROOT_PASSWORD=root_logodom
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - mynet